# Generated by Django 4.0.3 on 2022-04-07 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_completed']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='complete',
            new_name='is_completed',
        ),
    ]
